-- Table: public.exercise_record

-- DROP TABLE IF EXISTS public.exercise_record;

CREATE TABLE IF NOT EXISTS public.exercise_record
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    calories_burned double precision,
    created_at timestamp(6) without time zone,
    duration_minutes integer,
    exercise_name character varying(255) COLLATE pg_catalog."default",
    user_id bigint,
    CONSTRAINT exercise_record_pkey PRIMARY KEY (id),
    CONSTRAINT fkmb3kuvsephl3v4e9bqhyt2855 FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.exercise_record
    OWNER to postgres;

-- Table: public.meal_record

-- DROP TABLE IF EXISTS public.meal_record;

CREATE TABLE IF NOT EXISTS public.meal_record
(
    meal_record_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    calories double precision,
    carbs double precision,
    created_at timestamp(6) without time zone,
    fat double precision,
    food_name character varying(255) COLLATE pg_catalog."default",
    meal_type character varying(255) COLLATE pg_catalog."default",
    protein double precision,
    user_id bigint,
    CONSTRAINT meal_record_pkey PRIMARY KEY (meal_record_id),
    CONSTRAINT fkaijoeo6oj7f0wmqshe3vceqv FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.meal_record
    OWNER to postgres;

    -- Table: public.user_goal

-- DROP TABLE IF EXISTS public.user_goal;

CREATE TABLE IF NOT EXISTS public.user_goal
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    end_date date,
    start_date date,
    target_calories integer NOT NULL,
    target_weight double precision NOT NULL,
    user_id bigint,
    CONSTRAINT user_goal_pkey PRIMARY KEY (id),
    CONSTRAINT ukjr1bwksbeecjb2ajxtnb22loq UNIQUE (user_id),
    CONSTRAINT fkd09eq8bpxgy8p5wi7mjglujck FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_goal
    OWNER to postgres;

    -- Table: public.user_preference

-- DROP TABLE IF EXISTS public.user_preference;

CREATE TABLE IF NOT EXISTS public.user_preference
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    preferred_cuisine character varying(255) COLLATE pg_catalog."default",
    preferred_food character varying(255) COLLATE pg_catalog."default",
    user_id bigint,
    CONSTRAINT user_preference_pkey PRIMARY KEY (id),
    CONSTRAINT fk7mgxw6j2m7uvuk3svr9vsar8p FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_preference
    OWNER to postgres;

    -- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    birth_date date,
    gender character varying(255) COLLATE pg_catalog."default",
    height double precision,
    nickname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    weight double precision,
    diet_goal character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT uk2ty1xmrrgtn89xt7kyxx6ta7h UNIQUE (nickname)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;